/**
 * Generates version.ts from deno.json version field.
 */

const configRaw = await Deno.readTextFile('./deno.json');
const config = JSON.parse(configRaw);
const version = config.version ?? '0.0.0';

const content = `// This file is auto-generated by make_version.ts. Do not edit.
export const generatedVersion = '${version}';
`;

await Deno.writeTextFile('./src/version.ts', content);
console.log(`Version file generated: ${version}`);
